apiVersion: apps/v1beta2
kind: Deployment
metadata:
  namespace: toolbox
  name: toolbox-worker
  labels:
    app: toolbox-worker
spec:
  replicas: 2
  selector:
    matchLabels:
      app: toolbox-worker
  template:
    metadata:
      labels:
        app: toolbox-worker
    spec:
      terminationGracePeriodSeconds: 10
      containers:
      - name: toolbox-worker
        image: danielcoman/toolbox:latest
        imagePullPolicy: Always
        command:
          - /bin/sh
          - -c
          - 'until [ "imok" = "$(echo ruok)" ] ; do echo waiting ; sleep 1 ; done'
        env:
        - name: FOR_GODS_SAKE_PLEASE_REDEPLOY
          value: "232"
        resources:
          requests:
            cpu: 100m
            memory: 200Mi
          limits:
            cpu: 500m
            memory: 500Mi
        volumeMounts:
        - name: config
          mountPath: /config
      volumes:
      - name: config
        configMap:
          name: test-conf-volume
